### ISSUE TITLE
Help developing a REST Remote component

### ISSUE THREAD

**Issue by cheesykyle** [p3g4asus/home-assistant-custom-components#7]
Looking through your repo it's clear you have a good understanding of how the remote component works. Unfortunately the Remote entity type isn't really documented properly and I've been having a hard time wrapping my mind around it.

I'd like to have a Remote component that simply executes REST commands or even just acts as a proxy and executes other commands like the Universal Media Player component does. Do you have any interest in developing such a component or have any input on how to make something like this work?

Appreciate your input!

**Comment by p3g4asus** [comment]
Excuse me for late answer but I had to have a look to my code again to see if your component could be easily implemented. I think that it won't be difficult to implement what you are asking. The only concern is to express in yaml format the get/post queries you would like to send. Should the answer of rest server be analyzed in any way (maybe to know the status of a device)? I would be glad to help. But you should provide an example of rest request and how server output should be processed.

**Comment by cheesykyle** [comment]
Thanks for your reply. I think the component could actually be extremely simple by just triggering rest_commands already defined in Home Assistant. This would eliminate any special logic inside the remote component. For example, I have the following already defined in my Home Assistant configuration:

```yaml
rest_command:
  xbox_button_up:
    url: http://ip:port/device/liveid/input/dpad_up
```
So the send_command for the remote could just be the name of an already defined rest_command, ie 'xbox_button_up'. In my use case, I don't think worrying about anything returned form the server is necessary as the point of the Remote component is just to trigger actions.

**Comment by p3g4asus** [comment]
OK: I will work on that this weekend: Il should be pretty simple. I will try to design it as general as possible. I should also make my existing code PEP8 compliant. I designed this before knowing about PEP8.

**Comment by cheesykyle** [comment]
I really appreciate your interest in working on this, it's going to help me out a lot! Thanks.

**Comment by p3g4asus** [comment]
I commited a first version of remoterest component: you can find it in the development branch and in the master branch. It is still undocumented (sorry I had no time). To test it, place into the custom_components inside homeassistant configurations dir. Please note that, if homeassistant seems to hang at startup after placing the remoterest folder inside the custom_components folder, you should delete the manifest.json file inside the remoterest folder. Some versions of homeassistant don't like the manifest file in custom_components folder.
Example of configuration is:
```yaml
remote:
  - platform: remoterest
    name: friendly_name_of_remote
    timeout: 6
    keys:
      name_of_key1:
        method: GET
        url: http://url/to/use
        par:
          par1: ciao
          par2: bye
      name_of_key2:
        method: POSTFORM
        url: http://url/to/use/for2
        par:
          par1: ciao
          par2: bye
      name_of_key3:
        method: POSTJSON
        url: http://url/to/use/for/post/json/dump/of/params
        par:
          par1: ciao
          par2: 
             - d1
             - d2
             - d3
      name_of_key4:
        method: POSTBIN
        url: http://url/to/use/for/binary/data/specified/in/hex/format
        par:
          data: 52003F4EAADFEE34
```
To test it, you can use the lovelace interface to call the `remote.send_command` service with the entity `remote.friendly_name_of_remote` and one of the command specified (`name_of_key1`, `name_of_key2`, `name_of_key3` or `name_of_key4`) or a list of them.
I will document all the features of the component in spare time. Please tell me if you find problems or bug.
